#ifndef CONFIG_H
#define CONFIG_H

#define QSERIESHUNTER_MAJOR @QSERIESHUNTER_MAJOR@
#define QSERIESHUNTER_MINOR @QSERIESHUNTER_MINOR@
#define QSERIESHUNTER_PATCH @QSERIESHUNTER_PATCH@
#define QSERIESHUNTER_RELEASE @QSERIESHUNTER_RELEASE@

#endif // CONFIG_H
